version: "3.7"

services:
  db:
    build:
      context: ./.docker/mysql
      args:
        - MYSQL_TAG=${MYSQL_TAG}
    container_name: "${PROJECT_NAME}_db"
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 1G
    links:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"

  symfony:
    build:
      context: ./.docker/symfony
      args:
        - PHP_VERSION=${PHP_VERSION}
        - SYMFONY_CLI_VERSION=${SYMFONY_CLI_VERSION}
        - GROUP_ID=${GROUP_ID}
        - USER_ID=${USER_ID}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
        - GIT_EMAIL=${GIT_EMAIL}
        - GIT_USERNAME=${GIT_USERNAME}
    ports:
      - "${PHP_PORT}:9000"
    container_name: "${PROJECT_NAME}_symfony"
    user: ${USER_ID}:${GROUP_ID}
    environment:
      DATABASE_URL: ${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=${MYSQL_VERSION_MAJOR}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      MAILER_DSN: ${MAILER_DSN}
    links:
      - db
      - mailhog
    volumes:
      - ./project:/home/symfony/project
  
  nginx:
    build: 
      context: ./.docker/nginx
      args:
        - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT_SSL}:443"
    container_name: "${PROJECT_NAME}_nginx"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
      NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME}
      NGINX_SYMFONY_CONTAINER_NAME: ${PROJECT_NAME}_symfony
    links:
      - symfony
    volumes:
      - ./project:/home/symfony/project

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"

